name: simposi_app_v4
description: A social calendar for meeting new people

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

# Simposi Core Dependencies
  after_layout: ^1.1.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.2
  flutter_bloc: ^7.0.1
  flutter_compass: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  fluttertoast: ^8.0.7
  focused_menu: ^1.0.5
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.5
  google_map_location_picker:
    git:
      url: https://github.com/humazed/google_map_location_picker
      ref: 25deede4823145403718ab16795bfc3be604f46e
  google_maps_webservice: ^0.0.19
  html: ^0.15.0
  http_parser: ^4.0.0
  intl: ^0.17.0
  image_picker: ^0.8.0+3
  keyboard_dismisser: ^2.0.0
  location: ^4.1.1
  material_floating_search_bar: ^0.3.4
  page_transition: ^2.0.2
  permission_handler: ^8.0.0+1
  pin_code_fields: ^7.1.0
#  sms_autofill: ^2.0.0
  rxdart: ^0.26.0
  share: ^2.0.1
  shared_preferences: ^2.0.6
  table_calendar: ^3.0.0
  url_launcher: ^6.0.6

# Simposi Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true
# Use Material Design
  uses-material-design: true

# Simposi Assets
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/json/
    - assets/images/backgroundcalendar.png
    - assets/images/backgroundcompass.png
    - assets/images/backgroundbell.png
    - assets/images/profileplaceholder.png
    - assets/images/logosquare.png
    - assets/json/map_style.json
    - assets/images/eventcardbackground3.jpeg
    - assets/images/eventdetailsbackground.png
    - assets/images/airbaloon@3x.png
    - assets/images/ratingheart1.png
    - assets/images/ratinglike.png
    - assets/images/ratingneutral.png
    - assets/images/ratingmeh.png
    - assets/images/ratinghate.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

# Simposi Fonts
  fonts:
  # App Font
    - family: Muli
      fonts:
        - asset: assets/fonts/MuliRegular.ttf
  # Android Font ?
    - family: DM Serif Text
      fonts:
        - asset: assets/fonts/DMSerifTextItalic.ttf
          style: italic
  # Apple Font
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
  # Simposi Icons
    - family:  SimposiNav
      fonts:
        - asset: assets/fonts/SimposiNav.ttf
    - family:  Social
      fonts:
      - asset: assets/fonts/Social.ttf

  # IF ICONS STOP WORKING, SWITCH TO MASTER -> UPGRADE FLUTTER -> UPGRADE DART -> SAVE!!
  # ENSURE YOU ARE IMPORTING ICONS USING A PACKAGE IMPORT AND NOT A RELATIVE IMPORT - NO SPACES
  # REtURN TO FLUTTER CHANNEL STABLE AND RUN PUB GET TWICE TO CONFIRM THEN SAVE !!
  # https://stackoverflow.com/questions/52792630/flutter-custom-icons-not-rendering

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
