name: simposi_app_v4
description: A social calendar for meeting new people

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.6

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# Simposi Core Dependencies
  after_layout: ^1.1.0
  auto_route: ^3.2.4
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  flutter_bloc: ^8.0.1
  flutter_compass: ^0.7.0
  flutter_plugin_android_lifecycle: ^2.0.5
  fluttertoast: ^8.0.9
  focused_menu: ^1.0.5
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.3
  google_maps_webservice: "0.0.20-nullsafety.5" # DO NOT UPGRADE!
  html: ^0.15.0
  http_parser: ^4.0.0
  intl: ^0.17.0
  image_picker: ^0.8.4+11
  json_annotation: ^4.4.0
  keyboard_dismisser: ^2.0.1
  latlong2: ^0.8.1
  location: ^4.3.0
  localstorage: ^4.0.0+1
  material_floating_search_bar: ^0.3.7
  page_transition: ^2.0.5
  permission_handler: ^9.2.0
  pretty_dio_logger: ^1.1.1
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.3
  scrollable_positioned_list: ^0.2.3
  share_plus: ^4.0.3
  shared_preferences: ^2.0.13
  stream_transform: ^2.0.0
  table_calendar: ^3.0.5
  url_launcher: ^6.0.20

# Simposi Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  json_serializable: ^6.1.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# Locations
  generate: true

# Use Material Design
  uses-material-design: true

# Simposi Assets
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

# Simposi Fonts
  fonts:
  # App Font
    - family: Muli
      fonts:
        - asset: assets/fonts/MuliRegular.ttf
  # Android Font ?
    - family: DM Serif Text
      fonts:
        - asset: assets/fonts/DMSerifTextItalic.ttf
          style: italic
  # Apple Font
    - family: .AppleSystemUIFont
      fonts:
        - asset: assets/fonts/SFNS.ttf
  # Simposi Icons
    - family:  SimposiNav
      fonts:
        - asset: assets/fonts/SimposiNav.ttf
    - family:  Social
      fonts:
      - asset: assets/fonts/Social.ttf

  # IF ICONS STOP WORKING, SWITCH TO MASTER -> UPGRADE FLUTTER -> UPGRADE DART -> SAVE!!
  # ENSURE YOU ARE IMPORTING ICONS USING A PACKAGE IMPORT AND NOT A RELATIVE IMPORT - NO SPACES
  # REtURN TO FLUTTER CHANNEL STABLE AND RUN PUB GET TWICE TO CONFIRM THEN SAVE !!
  # https://stackoverflow.com/questions/52792630/flutter-custom-icons-not-rendering

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
