/// Flutter icons Simposi
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Simposi
///      fonts:
///       - asset: fonts/Simposi.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class SimposiIcons {
  SimposiIcons._();

  static const _kFontFam = 'SimposiIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addcircle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rsvp = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addcircleoutline = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carddeck = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alerts = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alerts2 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downbig = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leftopen = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leftbig = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightbig = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upbig = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upopen = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rightopen = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downopen = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot3 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infocircled = IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleleft = IconData(0xf104, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleright = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angleup = IconData(0xf106, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angledown = IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData primitivedotstroke = IconData(0xf332, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
