/// Flutter icons Social
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Social
///      fonts:
///       - asset: fonts/Social.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Social {
  Social._();

  static const _kFontFam = 'Social';
  static const String? _kFontPkg = null;

  static const IconData instagram_square = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_square = IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf08c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_alt = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_in = IconData(0xf0e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_messenger = IconData(0xf39f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_bulk = IconData(0xf674, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
